name: sampleapp1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: sample font
      fonts:
        - asset: fonts/ChelaOne-Regular.ttf
  uses-material-design: true

assets:
  - assets/image.jpg
  - assets/mini.jpg